#!/usr/bin/env python3
"""
================================================================================
FREDDIE MAC SFLLD: MODEL RISK MANAGEMENT & GOVERNANCE REPORT GENERATOR
================================================================================
Compiles technical specifications, out-of-time validation metrics, stress testing
results, and capital adequacy outputs into a comprehensive governance memo.
================================================================================
"""

import os
from datetime import datetime

os.makedirs("reports", exist_ok=True)
report_path = "reports/MODEL_RISK_MANAGEMENT_DOSSIER.md"

content = f"""# Institutional Mortgage Credit Risk Model & Capital Adequacy Dossier

**Target Dataset**: Freddie Mac Single-Family Loan-Level Dataset (SFLLD)  
**Execution Timestamp**: {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}  
**Model Framework**: Domain-Constrained Monotonic Gradient Boosted Trees (XGBoost)  
**Calibration Standard**: Out-of-Time Platt Scaling (Univariate Logistic Regression)  
**Capital Engine**: Vectorized Monte Carlo Credit Value-at-Risk (25,000 paths)  

---

## 1. Executive Summary & Regulatory Scope

This technical dossier documents the validation, stress testing, and capital modeling for the forward 12-month credit default model. All observations are measured at baseline observation snapshot $t=12$, enforcing an uncompromised non-look-ahead structure across four distinct macroeconomic regimes:
1. **GFC Stress Anchor (2006–2008)**: 3,157,335 loans (Systemic collapse, liquidity freeze, LGD calibration).
2. **Post-Crisis QM Baseline (2013–2017)**: 6,977,353 loans (Underwriting standard anchor, core training sample).
3. **Out-of-Time Pandemic Shock (2018–2019)**: 2,501,051 loans (CARES Act forbearance evaluation, Platt calibration).
4. **Increasing Rate Shock (2021–2022)**: 5,362,195 loans (Modern monetary tightening, rate lock-in, balance sheet portfolio).

---

## 2. Model Architecture & Monotonic Enforcement

The primary classifier enforces domain-consistent monotonicity to guarantee rational economic split behaviors:
* **FICO Score (`credit_score`)**: Monotonic constraint **-1** (strictly non-increasing risk).
* **Leverage & Burden (`original_ltv`, `original_cltv`, `original_dti`, `original_interest_rate`)**: Monotonic constraint **+1** (strictly non-decreasing risk).
* **Payment Performance (`snapshot_dq`, `upb_paydown_ratio`)**: Monotonic constraint **+1**.

### Validation & Discrimination Stability

| Historical Cohort | Loan Volume | Realized Default Rate | ROC-AUC | PR-AUC | Decile 1 Capture |
| :--- | :--- | :--- | :--- | :--- | :--- |
| **In-Time Train (2013–2017)** | 6,977,353 | 0.4317% | **0.8903** | 0.2309 | — |
| **Out-of-Time (2018–2019)** | 2,501,051 | 2.2906% | **0.7984** | 0.2417 | 47.18% |
| **GFC Anchor (2006–2008)** | 3,157,335 | 2.8215% | **0.8583** | 0.3096 | 58.14% |
| **Rate Shock (2021–2022)** | 5,362,195 | 0.6735% | **0.8581** | 0.2106 | 59.10% |

---

## 3. Probability Calibration (Platt Scaling)

Due to class weighting (`scale_pos_weight = 230.65`) applied to offset the low baseline event frequency, raw outputs represented rank margins. Applying out-of-time Platt calibration realigned probabilities without altering ROC-AUC rank-ordering:
* **Pre-Calibration Brier Score**: `0.138`
* **Post-Calibration Brier Score**: `0.020`
* **Calibrated Out-of-Time Mean PD**: `2.29%` (exact parity with realized default rate)

![Calibration & ROC Curves](figures/model_calibration_and_roc.png)

---

## 4. Empirical Downturn LGD Calibration

Downturn loss severity parameters were calculated directly from realized liquidations in the 2006–2008 GFC Stress Anchor:
$$\\text{{LGD}} = \\frac{{\\text{{forward\\_actual\\_loss}}}}{{\\text{{snapshot\\_upb}}}}$$
* **Realized Foreclosure Events with Populated Loss**: 3,848 loans
* **Empirical Downturn Mean ($\\mu_{{LGD}}$)**: **33.3149%**
* **Empirical Downturn Std Dev ($\\sigma_{{LGD}}$)**: **23.3959%**

---

## 5. Portfolio Value-at-Risk & Economic Capital Results

Conducted across the **$1.510 Trillion UPB** exposure of the Rate Shock Cohort (2021–2022):

| Capital Metric | Dollar Exposure ($ Billions) | Portfolio Loss Rate |
| :--- | :--- | :--- |
| **Total Portfolio UPB Exposure** | **$1,510.14B** | 100.00% |
| **Expected 12M Dollar Loss (EL)** | **$8.68B** | 0.5748% |
| **Value-at-Risk (95.0% VaR)** | **$9.31B** | 0.6165% |
| **Value-at-Risk (99.0% VaR)** | **$9.58B** | 0.6344% |
| **Value-at-Risk (99.9% VaR)** | **$9.90B** | 0.6556% |
| **Expected Shortfall (99.0% ES / CVaR)** | **$9.72B** | 0.6437% |
| **Unexpected Loss / Capital Requirement** | **$0.90B ($900.00M)** | 0.0596% |

![Loss Distribution](figures/portfolio_var_loss_distribution.png)

---
*Report auto-generated by the Freddie Mac SFLLD End-to-End Quantitative Risk Modeling Pipeline.*
"""

with open(report_path, "w") as f:
    f.write(content)

print(f"[✔] Technical Dossier generated at {report_path}")
